### ISSUE TITLE
Create Schema for Project

### ISSUE THREAD

**Issue by jared-skinner** [arfink/BISS-TEA#1]

**Comment by arfink** [comment]
Made the schema into its own document. We can edit it as necessary when we narrow down the spec to include char limits, types, etc.

**Comment by jared-skinner** [comment]
It would be good to have the following fields in every table

date_created
date_modified
deleted

The last one is so we can "delete" without actually loosing data.

**Comment by arfink** [comment]
Okay.

**Comment by arfink** [comment]
I am going to close this, since we have a starter schema created. Huzzah!
