### ISSUE TITLE
Create BISS icon

### ISSUE THREAD

**Issue by jared-skinner** [arfink/BISS-TEA#10]

**Comment by Sanjurjo7** [comment]
![tea64](https://cloud.githubusercontent.com/assets/9040826/12520856/f033a88a-c114-11e5-9752-ed3d72258d8d.png)
Done

**Comment by jared-skinner** [comment]
@Sanjurjo7 could you add the icon to the images foldes?

**Comment by Sanjurjo7** [comment]
This one is finished.
