### ISSUE TITLE
Design PHP infrastructure 

### ISSUE THREAD

**Issue by jared-skinner** [arfink/BISS-TEA#2]

**Comment by Sanjurjo7** [comment]
Let's get our HTML template squared away before we start hacking it to PHP bits.

**Comment by arfink** [comment]
Agreed.

**Comment by jared-skinner** [comment]
I have a php handling function build into index.php.  it takes the given url and grabs the html template file and php files which go with them.  It then takes the processed output and shoves it into the main template file and echos the whole thing.

The big trick is ==body== in the main html template file.  this gets replaced with the page's contents.
