### ISSUE TITLE
Create directory structure

### ISSUE THREAD

**Issue by jared-skinner** [arfink/BISS-TEA#3]

**Comment by jared-skinner** [comment]
My thoughts on this are as follows:

root - 
_____|
_____| - assets (for any external tools we are using.  e.g. jquery, bootstrap, etc...)
_____| - php -
____________| - ajax (cuz, what's a site without ajax?)
____________| - pages (the php for generating individual pages)
____________| - actions (any actions which aren't async.)
_____| - templates (html templates)
_____| - styles (css and the like)
_____| - images
_____| - schema (i am not sure where this will belong long term, but at least this gives it a home)
_____| - js (for any js we want to share between html pages)

(sorry for the underscores, gh was flattening my indenting)

It's a start.  What do you think?

**Comment by arfink** [comment]
I think schema would be good, or call it docs.

**Comment by Sanjurjo7** [comment]
This works, I'll go update my HTML real quick.
