### ISSUE TITLE
Update mysql schema with appropriate data and table types

### ISSUE THREAD

**Issue by arfink** [arfink/BISS-TEA#8]

**Comment by arfink** [comment]
I am thinking we can just stick with the InnoDB table type for MySQL as it's the default and we don't have much reason to use anything else in this situation.

**Comment by Sanjurjo7** [comment]
Do we want to stick with MySQL or use MariaDB. Same command calls, mostly, but added functionality and open source.

**Comment by arfink** [comment]
MySQL isn't open source? I initially wanted to go with MySQL because it's in my job req, but MariaDB would likely be fine too IMO.

**Comment by Sanjurjo7** [comment]
Pretty much anything we do in MariaDB would be cross applicable.

**Comment by arfink** [comment]
Can we get Otto to use MariaDB?

**Comment by jared-skinner** [comment]
I will check this evening.

**Comment by arfink** [comment]
If Otto will play nice, I would love to use MariaDB because Oracle is a den of scumbaggery, but if not, I say we stick with MySQL because my laziness is more powerful than my moral conviction on FOSS.

**Comment by jared-skinner** [comment]
since Otto seems to be earlier in its development than i had initially thought (after a couple hours I haven't been able to get the dang thing to work) i think just spinning up a dev vm from scratch would work best.  with that in mind MariaDB sounds like a fine idea.

**Comment by arfink** [comment]
The database has been designed, and barring any issues, should be more or less where we want it to be. Closed.
